### ISSUE TITLE
About codes update.

### ISSUE THREAD

**Issue by ElliottYan** [zhengzx-nlp/dynamic-nmt#1]
Hi,
I'm currently focusing on NMT and found your paper "Dynamic Past and Future for Neural Machine Translation" very interesting. 

I'm wondering if you recently have a plan to release the source code?

Thx.

**Comment by zhengzx-nlp** [comment]
Hi Elliott,

Thanks for your interest in our work. Yes the code will be released. However, because I am now a bit busy with the recent research project and conference rebuttal, I will, unfortunately, have to update the code a bit later, probably by the end of this month. Stay tuned and sorry for that inconvenience. 

zaixiang

**Comment by ElliottYan** [comment]
OK, cool. Looking forward to your updates. 
Thanks in advance. 

Elliott
